package compiler.helper;

public enum SymbolType {
//	CARD, CHARACTER, GAME_DEFINITION, BUILD_IN, KEYWORD,
//	LOCAL_VARIABLE, CARD_VARIABLE, CHARACTER_VARIABLE, CHARACTER_SKILL,
//	LOCAL_CARD_DECLARE,
//	UNDEFINED
	JAVA, KEYWORD, BUILD_IN, GAME, CARD_NAME, CHARACTER_NAME, 
	CARD_VARIABLE, CHARACTER_VARIABLE, CHARACTER_SKILL, LOCAL_CARD
}
