/* The following code was generated by JFlex 1.5.1 */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 2000 Gerwin Klein <lsf@jflex.de>                          *
 * All rights reserved.                                                    *
 *                                                                         *
 * Thanks to Larry Bell and Bob Jamison for suggestions and comments.      *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.1
 * from the specification file <tt>GameWizard.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\51\1\40\1\40\25\0\1\6\1\45\1\32\2\0\1\41"+
    "\1\47\1\0\1\41\1\41\1\41\1\41\1\41\1\30\1\41\1\41"+
    "\12\31\1\41\1\41\1\44\1\42\1\43\2\0\2\37\1\16\14\37"+
    "\1\26\2\37\1\35\7\37\1\41\1\0\1\41\1\41\1\12\1\0"+
    "\1\10\1\36\1\13\1\1\1\2\1\3\1\7\1\17\1\4\1\37"+
    "\1\33\1\24\1\11\1\5\1\22\1\23\1\37\1\14\1\15\1\20"+
    "\1\21\1\34\1\50\1\27\1\25\1\37\1\41\1\46\1\41\1\41"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\5\2\1\3\10\2\1\4\1\5\1\1"+
    "\3\2\5\4\2\1\1\2\1\6\5\2\1\7\1\10"+
    "\12\2\1\0\1\11\3\2\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\10\2\1\20\21\2\1\21\2\2\1\22"+
    "\6\2\1\23\1\24\1\25\1\2\1\26\1\2\1\27"+
    "\3\2\1\30\1\31\5\2\1\32\1\33\2\2\1\34"+
    "\1\2\1\35\3\2\1\36\3\2\1\37\1\40\1\0"+
    "\1\41\6\2\2\0\6\2\3\0\1\2\1\42\1\2"+
    "\1\43\2\2\3\0\4\2\1\44\2\0\2\2\1\45"+
    "\1\2\1\46\1\0\2\2\1\47\1\0\1\2\1\50"+
    "\1\0\1\51\2\0\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276"+
    "\0\u02a0\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\52\0\u0372"+
    "\0\u039c\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\52\0\u0498"+
    "\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u017a\0\u056a\0\u0594\0\u05be"+
    "\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e"+
    "\0\u02ca\0\52\0\u0738\0\u0762\0\u078c\0\52\0\52\0\52"+
    "\0\52\0\52\0\52\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u085e"+
    "\0\u0888\0\u08b2\0\u08dc\0\u017a\0\u0906\0\u0930\0\u095a\0\u0984"+
    "\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4"+
    "\0\u0afe\0\u0b28\0\u0b52\0\u0b7c\0\u0ba6\0\u017a\0\u0bd0\0\u0bfa"+
    "\0\u017a\0\u0c24\0\u0c4e\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\u017a"+
    "\0\u017a\0\u017a\0\u0d20\0\u017a\0\u0d4a\0\u017a\0\u0d74\0\u0d9e"+
    "\0\u0dc8\0\u017a\0\u017a\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a"+
    "\0\u0ec4\0\u017a\0\u0eee\0\u0f18\0\u017a\0\u0f42\0\u017a\0\u0f6c"+
    "\0\u0f96\0\u0fc0\0\u017a\0\u0fea\0\u1014\0\u103e\0\u017a\0\u017a"+
    "\0\u1068\0\u017a\0\u1092\0\u10bc\0\u10e6\0\u1110\0\u113a\0\u1164"+
    "\0\u118e\0\u11b8\0\u11e2\0\u120c\0\u1236\0\u1260\0\u128a\0\u12b4"+
    "\0\u12de\0\u1308\0\u1332\0\u135c\0\u017a\0\u1386\0\u017a\0\u13b0"+
    "\0\u13da\0\u1404\0\u142e\0\u1458\0\u1482\0\u14ac\0\u14d6\0\u1500"+
    "\0\52\0\u152a\0\u1554\0\u157e\0\u15a8\0\u017a\0\u15d2\0\52"+
    "\0\u15fc\0\u1626\0\u1650\0\u017a\0\u167a\0\u16a4\0\u017a\0\u16ce"+
    "\0\u017a\0\u16f8\0\u1722\0\52";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\2\1\12\1\14\1\15\1\16\1\12"+
    "\1\17\5\12\1\20\1\12\1\21\1\22\1\23\1\12"+
    "\1\24\1\25\1\26\1\12\1\10\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\53\0\1\12"+
    "\1\40\3\12\1\0\16\12\1\41\2\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\15\12"+
    "\1\42\3\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\1\12\1\43\11\12\1\44\5\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\2\12"+
    "\1\45\1\12\1\46\1\0\21\12\1\0\1\12\1\0"+
    "\5\12\10\0\1\12\2\0\5\12\1\0\12\12\1\47"+
    "\6\12\1\0\1\12\1\0\5\12\10\0\1\12\7\0"+
    "\1\10\31\0\1\10\12\0\5\12\1\0\1\12\1\50"+
    "\17\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\5\12\1\0\21\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\1\12\1\51\3\12\1\0\1\12\1\52"+
    "\17\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\5\12\1\0\13\12\1\53\5\12\1\0\1\12\1\0"+
    "\5\12\10\0\1\12\2\0\5\12\1\0\21\12\1\0"+
    "\1\12\1\0\1\54\4\12\10\0\1\12\2\0\5\12"+
    "\1\0\1\12\1\55\17\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\5\12\1\56\4\12"+
    "\1\57\6\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\15\12\1\60\3\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\32\0\1\22\20\0\32\61"+
    "\1\62\17\61\1\0\5\12\1\0\13\12\1\63\5\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\11\12\1\64\7\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\13\12\1\65\5\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\43\0\1\66"+
    "\51\0\1\67\51\0\1\70\51\0\1\71\55\0\1\72"+
    "\52\0\1\73\3\0\5\12\1\0\10\12\1\74\10\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\2\12"+
    "\1\75\2\12\1\0\1\12\1\76\17\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\3\12\1\77\1\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\6\12\1\100\12\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\15\12"+
    "\1\101\3\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\5\12\1\102\13\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\3\12\1\103\1\12"+
    "\1\0\11\12\1\104\7\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\2\12\1\105\16\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\2\12\1\106\16\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\11\12\1\107\7\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\20\12\1\110\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\5\12\1\0\12\12\1\111\6\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\3\12\1\112"+
    "\1\12\1\0\21\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\5\12\1\0\5\12\1\113\13\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\12\12\1\114\6\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\5\12\1\0\5\12\1\115\13\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\1\12\1\116\17\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\3\12\1\117\1\12\1\0\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\5\12\1\120\13\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\5\12\1\0\13\12\1\121\5\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\3\12\1\122"+
    "\1\12\1\0\21\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\3\12\1\123\1\12\1\0\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\15\12\1\124\3\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\4\12\1\125\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\1\12\1\126\3\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\6\12\1\127\12\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\1\12\1\130\3\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\11\12\1\131\7\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\3\12"+
    "\1\132\15\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\1\12\1\133\3\12\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\10\12"+
    "\1\134\10\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\3\12\1\135\1\12\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\4\12\1\136\1\0"+
    "\21\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\5\12\1\0\15\12\1\137\3\12\1\0\1\12\1\0"+
    "\5\12\10\0\1\12\2\0\1\140\4\12\1\0\21\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\1\12"+
    "\1\141\3\12\1\0\21\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\4\12\1\142\1\0\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\16\12\1\143\2\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\1\144\4\12\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\3\12\1\145\1\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\15\12\1\146\3\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\15\12"+
    "\1\147\3\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\4\12\1\150\1\0\21\12\1\0\1\12\1\0"+
    "\5\12\10\0\1\12\2\0\1\12\1\151\3\12\1\0"+
    "\21\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\5\12\1\0\1\152\20\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\1\12\1\153\3\12\1\0\21\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\1\12\1\154\17\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\13\12\1\155\5\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\3\12\1\156\15\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\13\12\1\157\5\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\2\12\1\160\16\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\1\161\4\12\1\0\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\15\12\1\162\3\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\1\12\1\163\3\12\1\0\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\4\12\1\164"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\1\12\1\165\3\12\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\1\12\1\166\3\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\5\12\1\167\13\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\4\12"+
    "\1\170\14\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\2\12\1\171\2\12\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\4\12\1\172\1\0"+
    "\21\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\1\173\4\12\1\0\21\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\12\12\1\174\6\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\3\12\1\175\15\12\1\0\1\12\1\0\2\12"+
    "\1\176\2\12\10\0\1\12\2\0\5\12\1\0\5\12"+
    "\1\177\13\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\1\200\20\12\1\0\1\12\1\0"+
    "\5\12\10\0\1\12\2\0\5\12\1\201\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\10\12\1\202\10\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\5\12\1\0\3\12\1\203\15\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\1\12\1\204\17\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\5\12\1\0\2\12\1\205\16\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\1\12\1\206"+
    "\3\12\1\0\21\12\1\0\1\12\1\0\3\12\1\207"+
    "\1\12\10\0\1\12\2\0\5\12\1\0\12\12\1\210"+
    "\6\12\1\0\1\12\1\0\5\12\10\0\1\12\10\0"+
    "\1\211\3\0\1\212\37\0\5\12\1\0\14\12\1\213"+
    "\4\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\5\12\1\0\2\12\1\214\16\12\1\0\1\12\1\0"+
    "\5\12\10\0\1\12\2\0\5\12\1\0\3\12\1\215"+
    "\15\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\4\12\1\216\1\0\21\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\1\12\1\217\3\12\1\0\21\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\2\12\1\220\16\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\11\0\1\221\51\0\1\222\6\0\1\223"+
    "\33\0\5\12\1\0\15\12\1\224\3\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\1\12\1\225\3\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\5\12\1\226\13\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\1\227\4\12\1\0"+
    "\21\12\1\0\1\12\1\0\5\12\10\0\1\12\2\0"+
    "\5\12\1\0\1\230\20\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\5\12\1\0\2\12\1\231\16\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\12\0\1\232"+
    "\54\0\1\233\45\0\1\234\42\0\5\12\1\0\1\12"+
    "\1\235\17\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\13\12\1\236\5\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\3\12\1\237\1\12"+
    "\1\0\21\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\2\0\5\12\1\0\1\12\1\240\17\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\3\0\1\241\50\0\1\242"+
    "\64\0\1\243\36\0\5\12\1\0\16\12\1\244\2\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\5\12"+
    "\1\0\12\12\1\245\6\12\1\0\1\12\1\0\5\12"+
    "\10\0\1\12\2\0\4\12\1\246\1\0\21\12\1\0"+
    "\1\12\1\0\5\12\10\0\1\12\2\0\5\12\1\0"+
    "\5\12\1\247\13\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\16\0\1\250\44\0\1\251\42\0\1\12\1\252"+
    "\3\12\1\0\21\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\2\0\4\12\1\253\1\0\21\12\1\0\1\12"+
    "\1\0\5\12\10\0\1\12\2\0\5\12\1\0\16\12"+
    "\1\254\2\12\1\0\1\12\1\0\5\12\10\0\1\12"+
    "\14\0\1\255\37\0\5\12\1\0\5\12\1\256\13\12"+
    "\1\0\1\12\1\0\5\12\10\0\1\12\2\0\1\257"+
    "\4\12\1\0\21\12\1\0\1\12\1\0\5\12\10\0"+
    "\1\12\21\0\1\260\32\0\5\12\1\0\6\12\1\261"+
    "\12\12\1\0\1\12\1\0\5\12\10\0\1\12\3\0"+
    "\1\262\63\0\1\263\52\0\1\264\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5964];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\24\1\1\11\7\1\1\11\21\1\1\0"+
    "\1\11\3\1\6\11\105\1\1\0\7\1\2\0\6\1"+
    "\3\0\6\1\3\0\4\1\1\11\2\0\4\1\1\11"+
    "\1\0\3\1\1\0\2\1\1\0\1\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.err.println("Error: unexpected character '"+yytext()+"'"); return -1;
          }
        case 43: break;
        case 2: 
          { yyparser.yylval = new ParserVal(yytext()); return Parser.ID;
          }
        case 44: break;
        case 3: 
          { /*do nothing*/
          }
        case 45: break;
        case 4: 
          { return (int) yycharat(0);
          }
        case 46: break;
        case 5: 
          { yyparser.yylval = new ParserVal(Integer.parseInt(yytext()));
		return Parser.INTEGER;
          }
        case 47: break;
        case 6: 
          { System.err.println("Sorry, backspace doesn't work");
          }
        case 48: break;
        case 7: 
          { return Parser.IF;
          }
        case 49: break;
        case 8: 
          { return Parser.IN;
          }
        case 50: break;
        case 9: 
          { yyparser.yylval = new ParserVal(yytext()); return Parser.STRING;
          }
        case 51: break;
        case 10: 
          { return Parser.OP_EQ;
          }
        case 52: break;
        case 11: 
          { return Parser.OP_GE;
          }
        case 53: break;
        case 12: 
          { return Parser.OP_LE;
          }
        case 54: break;
        case 13: 
          { return Parser.OP_NE;
          }
        case 55: break;
        case 14: 
          { return Parser.OP_LOR;
          }
        case 56: break;
        case 15: 
          { return Parser.OP_LAND;
          }
        case 57: break;
        case 16: 
          { return Parser.DECLR_INT;
          }
        case 58: break;
        case 17: 
          { return Parser.ELSE;
          }
        case 59: break;
        case 18: 
          { return Parser.INIT;
          }
        case 60: break;
        case 19: 
          { return Parser.CARD;
          }
        case 61: break;
        case 20: 
          { return Parser.TRUE;
          }
        case 62: break;
        case 21: 
          { return Parser.TURN;
          }
        case 63: break;
        case 22: 
          { return Parser.VOID;
          }
        case 64: break;
        case 23: 
          { return Parser.DECLR_BOOL;
          }
        case 65: break;
        case 24: 
          { return Parser.DYING;
          }
        case 66: break;
        case 25: 
          { return Parser.FALSE;
          }
        case 67: break;
        case 26: 
          { return Parser.ROUND;
          }
        case 68: break;
        case 27: 
          { return Parser.SKILL;
          }
        case 69: break;
        case 28: 
          { return Parser.WHILE;
          }
        case 70: break;
        case 29: 
          { return Parser.DEALER;
          }
        case 71: break;
        case 30: 
          { return Parser.METHOD;
          }
        case 72: break;
        case 31: 
          { return Parser.PLAYER;
          }
        case 73: break;
        case 32: 
          { return Parser.DECLR_STR;
          }
        case 74: break;
        case 33: 
          { return Parser.FOREACH;
          }
        case 75: break;
        case 34: 
          { return Parser.GAME_NM;
          }
        case 76: break;
        case 35: 
          { return Parser.ROUND_END;
          }
        case 77: break;
        case 36: 
          { return Parser.GAME_DF;
          }
        case 78: break;
        case 37: 
          { return Parser.ROUND_BEGIN;
          }
        case 79: break;
        case 38: 
          { return Parser.CARD_DF;
          }
        case 80: break;
        case 39: 
          { return Parser.ROUNDSUMMARY;
          }
        case 81: break;
        case 40: 
          { return Parser.MAX_ROUND;
          }
        case 82: break;
        case 41: 
          { return Parser.PLAYER_C;
          }
        case 83: break;
        case 42: 
          { return Parser.CHARACTER_DF;
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
